### ISSUE TITLE
customize proof-view theme

### ISSUE THREAD

**Issue by siegebell** [siegebell/vscoq#91]
* allow the user to provide a *.css file to override the theme.
* ideal solution: vscode provides a decent themeing API (Microsoft/vscode#14309)

**Comment by siegebell** [comment]
Instructions:
1. run "Coq: Customize proof-view styling"
2. edit proof-view.css
3. save the file
4. in the proof view, click "Refresh" (top left corner)
5. to reset the changes:
  * either delete proof-view.css or delete its contents
  * either run "Coq: Customize proof-view styling" or open a new proof view

**Comment by siegebell** [comment]
@jonleivent you'll want to delete the following items from proof-view.css:

```css
.hypotheses li:nth-child(odd) {
  background-color: rgba(255,255,255,0.04)
}
.vscode-light .hypotheses li:nth-child(odd) {
  background-color: rgba(0,0,0,0.02)
}
```

**Comment by jonleivent** [comment]
There is no "Coq:Customize..." in vscoq 0.2.3.

**Comment by siegebell** [comment]
It will be in 0.2.4 (to be released soon, hopefully)

**Comment by jonleivent** [comment]
Apparently, you removed those lines from proof-view.css for me.

How would I highlight evars (identifiers prefixed by "?" with no intervening whitespace) using proof-view.css?

**Comment by siegebell** [comment]
Oh whoops, I didn't intend to include proof-view.css in the package (it's generated automatically from default-proof-view.css).

If you're using Coq 8.6, then coqtop provides richpp annotations that you can style:
```css
.vscode-dark .richpp .constr-evar {
  color: darkorange;
  font-style: italic;
}
```

If you're using 8.5, there's no nice way to get syntax highlighting applied to evars :(

**Comment by jonleivent** [comment]
I would very much like to learn more about the settings in proof-view.css.  Is there some doc somewhere?

**Comment by siegebell** [comment]
No documentation; just lots of hacky code putting up a semblance of a UI (this was my first experience using jQuery...) I'm happy to answer questions, though.

**Comment by jonleivent** [comment]
Suppose I want to put a border around each hypothesis label - how do I do that?

**Comment by siegebell** [comment]
```css
.hypotheses .hypothesis .ident {
  border: 1px solid red;
}
```
